# Etapa 1: build de la app
FROM node:18 AS builder

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Etapa 2: copiar el build al volumen compartido (como contenedor dummy)
FROM alpine

# Crear directorio de destino que será mapeado como volumen
VOLUME ["/build"]
WORKDIR /build

COPY --from=builder /app/dist .

CMD ["sleep", "infinity"]
